# Site settings
title: Emma Loos
email: emmasponsorloop@outlook.com
instagram_username: samenvooremma
author: Mirelle en Edwin Loos
description: ""
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.emmaloos.nl" # the base hostname & protocol for your site, e.g. http://example.com
contacturl: "mailto:emmasponsorloop@outlook.com"
doneerurl: "https://betaalverzoek.rabobank.nl/betaalverzoek/?id=XqAcgJQ2RC6XodDJkiR0Qg"
inschrijfurl: "https://docs.google.com/forms/d/e/1FAIpQLSeGxkPpnSOvD9rU0x2rxgNJKMVzKEF8adS7lfRtxbjvlm_9GA/viewform?usp=dialog"
nieuwsbriefurl: "https://docs.google.com/forms/d/e/1FAIpQLSenK6r9ADBG_ysQ2fu75xHyYXu5LPucJTVSSPrct4lNasmZeA/viewform?usp=dialog"
veilingurl: "https://emmaloos.itsam.nl"

# Build settings
# theme: jekyll-theme-clean-blog # minima
# plugins:
#   - jekyll-feed

