# Site settings
title: Emma Loos
email: info@emmaloos.nl
author: Mirelle en Edwin Loos
description: >- # this means to ignore newlines until "baseurl:"
  Maak kennis met Emma.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.emmaloos.nl" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
# theme: jekyll-theme-clean-blog # minima
plugins:
  - jekyll-feed

